const categories = {
    categorie1: [
        { name: "Produit 1", description: "Casque audio stylé pour jeunes filles 1", price: "3000fr", img: "produita1.jpg" },
        { name: "Produit 2", description: "Casque audio JBL pour mec stylé", price: "3500fr", img: "produita2.jpg" },
        { name: "Produit 3", description: "Bleutooth JBL AIR F9 pro+ ", price: "3500fr", img: "produita3.jpg" },
        { name: "Produit 4", description: "Casque audio JBL B29 stylé", price: "3500fr", img: "produita4.jpg" },
        { name: "Produit 5", description: "Casque audio P9", price: "3000fr", img: "produita5.jpg" },
        { name: "Produit 6", description: "Bleutooth I88", price: "3000fr", img: "produita6.jpg" },
        { name: "Produit 7", description: "Bleutooth Pro 5s", price: "3500fr", img: "produita7.jpg" },
        { name: "Produit 8", description: "Bleutooth samsung galaxy 2020", price: "3500fr", img: "produita8.jpg" },
        { name: "Produit 9", description: "Bleutooth pratique pour le travail", price: "3500fr", img: "produita9.jpg" },
        { name: "Produit 10", description: "Bleutooth parfait pour les travailleurs", price: "3500fr", img: "produita10.jpg" },
        { name: "Produit 11", description: "Casque audio R9 simple et stylé", price: "3000fr", img: "produita11.jpg" },
        { name: "Produit 12", description: "Casque audio oraimo B29", price: "3000fr", img: "produita12.jpg" },
        { name: "Produit 13", description: "Bleutooth stylé ", price: "3000fr", img: "produita13.jpg" },
        { name: "Produit 14", description: "Bleutooth JBL Air F9 Pro 3", price: "3500fr", img: "produita14.jpg" },
        //{ name: "Produit 15", description: "Casque audio JBL pour mec stylé", price: "3500fr", img: "produitaa15.jpg" },
       // { name: "Produit 16", description: "Casque audio JBL pour mec stylé", price: "3500fr", img: "produita16.jpg" },
    ],
    categorie2: [
        { name: "Produit 1", description: "Écouteur LG RG-66 ", price: "600fr", img: "produitb1.jpg" },
        { name: "Produit 2", description: "Écouteur HEPU ", price: "600fr", img: "produitb2.jpg" },
        { name: "Produit 3", description: "Écouteur oraimo", price: "600fr", img: "produitb3.jpg" },
        { name: "Produit 4", description: "Écouteur pour iOS et androïd", price: "1000fr", img: "produitb4.jpg" },
        { name: "Produit 5", description: "Écouteur simple de qualité", price: "600fr", img: "produitb5.jpg" },
        { name: "Produit 6", description: "Incassables de toutes marques sauf iOS", price: "600fr", img: "produitb6.jpg" },
        { name: "Produit 7", description: "incassables fumés toutes marques sauf iOS", price: "700fr", img: "produitb7.jpg" },
    ],
    categorie3: [
        { name: "Produit 1", description: "Power bank de qualité", price: "5000fr pour 20000mAh et 7000fr pour 30000mAh", img: "produitc1.jpg" },
        { name: "Produit 2", description: "Power Bank avec plaque modulable. très pratique", price: "7500fr", img: "produitc2.jpg" },
        { name: "Produit 3", description: "Power Bank HP975 20000mAh", price: "5000fr", img: "produitc3.jpg" },
        { name: "Produit 4", description: "Power Bank HP255 50000mAh", price: "11000fr", img: "produitc4.jpg" },
        { name: "Produit 5", description: "Power Bank HP980 30000mAh", price: "7000fr", img: "produitc5.jpg" },
        { name: "Produit 6", description: "Power Bank HP211 60000mAh", price: "17500fr", img: "produitc6.jpg" },
        { name: "Produit 7", description: "Power Bank HP990 40000mAh", price: "10000fr", img: "produitc7.jpg" },
        { name: "Produit 8", description: "Power Bank HP247 30000mAh", price: "7000fr", img: "produitc8.jpg" },
        { name: "Produit 9", description: "Power Bank HP972 20000mAh", price: "5000fr", img: "produitc9.jpg" },
        { name: "Produit 10", description: "Power Bank HEPU stylé 30000mAh", price: "8000", img: "produitc10.jpg" },
    ],
    categorie4: [
        { name: "Produit 1", description: "Paneau photovoltaïque 400W état neuf dans carton ", price: "90000fr", img: "produitd1.jpg" },
        { name: "Produit 2", description: "Paneau photovoltaïque 275W état neuf dans carton", price: "70000fr", img: "produitd2.jpg" },
        { name: "Produit 3", description: "Paneau photovoltaïque 320W état neuf dans carton", price: "80000fr", img: "produitd3.jpg" },
        { name: "Produit 4", description: "Controleur de charge", price: "5000fr", img: "produitd4.jpg" },
        { name: "Produit 5", description: "DC charger pratique pour les batteries", price: "1000fr", img: "produitd5.jpg" },
        { name: "Produit 6", description: "DC charger M02 pour batteries ", price: "1000fr", img: "produitd6.jpg" },
        { name: "Produit 7", description: "Paneau photovoltaïque 150W état neuf dans carton", price: "50000fr", img: "produitd7.jpg" },
        { name: "Produit 8", description: "Paneau photovoltaïque 100W état neuf dans carton", price: "35000fr", img: "produitd8.jpg" },
        { name: "Produit 9", description: "Paneau photovoltaïque 50W état neuf dans carton", price: "20000fr", img: "produitd9.jpg" },
        { name: "Produit 10", description: "Prise pour installation solaire", price: "1000fr", img: "produitd10.jpg" },
        { name: "Produit 11", description: "Batterie Kidar Power 100(12V100AH)", price: "70000fr", img: "produitd11.jpg" },
        { name: "Produit 12", description: "Batterie Kidar Power 150(12V150AH)", price: "95000fr", img: "produitd12.jpg" },
        { name: "Produit 13", description: "Batterie Kidar Power 200(12V200AH)", price: "155000fr", img: "produitd13.jpg" },
        { name: "Produit 14", description: "Batterie Kidar Power 12V300AH mini", price: "22000fr", img: "produitd14.jpg" },
        { name: "Produit 15", description: "Kidar Power 12V200AH mini", price: "18000fr", img: "produitd15.jpg" },
        { name: "Produit 16", description: "DC charger pour batteries solaire", price: "1000fr", img: "produitd16.jpg" },
        { name: "Produit 17", description: "Prise pour installation solaire", price: "1000fr", img: "produitd17.jpg" },
        { name: "Produit 18", description: "DC charger prise PNA-03U ", price: "1000fr", img: "produitd18.jpg" },
        { name: "Produit 19", description: "convertisseur de tres bonne qualité", price: "5000fr", img: "produitd19.jpg" },
    ],
    categorie5: [
        { name: "Produit 1", description: "X-cable manetique et multiprise", price: "1000fr", img: "produite1.jpg" },
        { name: "Produit 2", description: "Cable court facile à transporter ", price: "300fr", img: "produite2.jpg" },
        { name: "Produit 3", description: "Chargeur iphone Original", price: "1500fr", img: "produite3.jpg" },
        { name: "Produit 4", description: "Chargeur", price: "1500fr", img: "produite4.jpg" },
        { name: "Produit 5", description: "Chargeur multibranchement très pratique", price: "1000fr", img: "produite5.jpg" },
        { name: "Produit 6", description: "Chargeur HP811", price: "1000fr", img: "produite6.jpg" },
        { name: "Produit 7", description: "Cables longs", price: "600fr", img: "produite7.jpg" },
        { name: "Produit 8", description: "Cable original", price: "1000fr", img: "produite8.jpg" },
        { name: "Produit 9", description: "Chargeur VIP", price: "1000fr", img: "produite9.jpg" },
        { name: "Produit 10", description: "Chargeur durable de Haute game", price: "1000fr", img: "produite10.jpg" },
    ],
    categorie6: [
        { name: "Produit 1", description: "Boomeur avec torche et lampe intégré", price: "7000fr", img: "produitf1.jpg" },
        { name: "Produit 2", description: "Mini boomeur JBL avec un volume élevé et interessant", price: "3000fr", img: "produitf2.jpg" },
        { name: "Produit 3", description: "Boomeur W-VIP de qualité", price: "5000fr", img: "produitf3.jpg" },
        { name: "Produit 4", description: "Boomeur session LP-V", price: "3000fr", img: "produitf4.jpg" },
        { name: "Produit 5", description: "Boomeur W'UP W2", price: "5000fr", img: "produitf5.jpg" },
        { name: "Produit 6", description: "Lampe Africa Sun trè pratique avec plusieurs types d'allumage", price: "5500fr", img: "produitf6.jpg" },
        { name: "Produit 7", description: "Boomeur Sonac A8", price: "20000fr", img: "produitf7.jpg" },
        { name: "Produit 8", description: "Boomeur W-VIP", price: "5000fr", img: "produitf8.jpg" },
        { name: "Produit 9", description: "Boomeur 15W trè interessant", price: "5000fr", img: "produitf9.jpg" },
        { name: "Produit 10", description: "Lampe rechargeables et facile à transporter", price: "800fr", img: "produitf10.jpg" },
        { name: "Produit 11", description: "Boomeur W-UF", price: "5000fr", img: "produitf11.jpg" },
        { name: "Produit 12", description: "Boomeur LP", price: "3500fr", img: "produitf12.jpg" },
        { name: "Produit 13", description: "Boomeur stylé de qualité", price: "4500fr", img: "produitf13.jpg" },
        { name: "Produit 14", description: "Camerera de surveillance l'une des meilleures expériences", price: "22000fr", img: "produitf14.jpg" },
    ],
    categorie7: [
        { name: "Produit 1", description: "Redmi 14C 256G/16g", price: "85000fr", img: "produitg1.jpg" },
        { name: "Produit 2", description: "Infinix HOT 50i", price: "62000", img: "produitg2.jpg" },
        { name: "Produit 3", description: "Redmi Note 13 Pro+ 5G", price: "190000fr", img: "produitg3.jpg" },
        { name: "Produit 4", description: "TECNO POP 9", price: "53000fr", img: "produitg4.jpg" },
        { name: "Produit 5", description: "Itel S24", price: "67000fr", img: "produitg5.jpg" },
        { name: "Produit 6", description: "Redmi 13c", price: "57000fr", img: "produitg6.jpg" },
        { name: "Produit 7", description: "Redmi A3", price: "55000fr", img: "produitg7.jpg" },
        { name: "Produit 8", description: "Itel A70", price: "45000fr", img: "produitg8.jpg" },
        { name: "Produit 9", description: "Itel A80", price: "48000fr", img: "produitg9.jpg" },
    ],
};
